services:
  db:
    image: postgres:16
    container_name: estoque-db
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - estoque_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estoque
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
volumes:
  estoque_data:
